// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4bwAjTIzryg56hrZ2-ld9kzY0hxSX0A',
    appId: '1:1091908852133:web:3987f2ca0d1c9f0d12f04c',
    messagingSenderId: '1091908852133',
    projectId: 'serverless-queue',
    authDomain: 'serverless-queue.firebaseapp.com',
    storageBucket: 'serverless-queue.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe8qGqlNXSMGmBvbWe1nOMA7RdaYIoYY0',
    appId: '1:1091908852133:android:0e31a6c7dffb076e12f04c',
    messagingSenderId: '1091908852133',
    projectId: 'serverless-queue',
    storageBucket: 'serverless-queue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOndOKr4Mk-pEeN9h1qeo4HDhGEsJytGo',
    appId: '1:1091908852133:ios:9aba8d38090adf0e12f04c',
    messagingSenderId: '1091908852133',
    projectId: 'serverless-queue',
    storageBucket: 'serverless-queue.firebasestorage.app',
    iosBundleId: 'com.dna.antrian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOndOKr4Mk-pEeN9h1qeo4HDhGEsJytGo',
    appId: '1:1091908852133:ios:9aba8d38090adf0e12f04c',
    messagingSenderId: '1091908852133',
    projectId: 'serverless-queue',
    storageBucket: 'serverless-queue.firebasestorage.app',
    iosBundleId: 'com.dna.antrian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj4bwAjTIzryg56hrZ2-ld9kzY0hxSX0A',
    appId: '1:1091908852133:web:06b1f6a81f98940212f04c',
    messagingSenderId: '1091908852133',
    projectId: 'serverless-queue',
    authDomain: 'serverless-queue.firebaseapp.com',
    storageBucket: 'serverless-queue.firebasestorage.app',
  );

}