import 'package:flutter/material.dart';
import 'package:flutter_filament/flutter_filament.dart';
import '../../data/models/{{name_snake}}.dart';
import '../../data/services/{{name_snake}}/{{name_snake}}_services.dart';

/// {{name.pascalCase()}}Resource — Filament-style resource for [{{name.pascalCase()}}].
/// Generated by the `resource` brick; edit `form()` and `table()` to tune
/// the UI, or subclass if you need conditional behavior.
class {{name.pascalCase()}}Resource extends Resource<{{name.pascalCase()}}> {
  @override
  String get slug => '{{name_snake}}';

  @override
  String get label => '{{label}}';

  @override
  String get pluralLabel => '{{pluralLabel}}';

  @override
  IconData get icon => Icons.{{icon}};{{#has_group}}

  @override
  String? get navigationGroup => '{{group}}';{{/has_group}}

  @override
  DataSource<{{name.pascalCase()}}> get dataSource =>
      {{name.pascalCase()}}Services.dataSource;

  @override
  String recordId({{name.pascalCase()}} record) => record.id;

  @override
  String recordTitle({{name.pascalCase()}} record) =>
      record.{{first_field}}?.toString() ?? record.id;

  @override
  Map<String, dynamic> toFormData({{name.pascalCase()}} record) => record.toJson();

  @override
  FormSchema form(ResourceContext<{{name.pascalCase()}}> ctx) => FormSchema(
        columns: 2,
        components: [{{#fields_list}}
          {{#is_string}}TextInput(
            name: '{{field_name}}',
            label: '{{field_label}}',
            required: true,
          ),{{/is_string}}{{#is_numeric}}NumberInput(
            name: '{{field_name}}',
            label: '{{field_label}}',
            allowDecimal: {{allow_decimal}},
          ),{{/is_numeric}}{{#is_bool}}Toggle(
            name: '{{field_name}}',
            label: '{{field_label}}',
          ),{{/is_bool}}{{#is_datetime}}DatePickerInput(
            name: '{{field_name}}',
            label: '{{field_label}}',
          ),{{/is_datetime}}{{/fields_list}}
        ],
      );

  @override
  TableSchema<{{name.pascalCase()}}> table() => TableSchema<{{name.pascalCase()}}>(
        columns: [{{#fields_list}}
          {{#is_bool}}BooleanColumn<{{model_name}}>(
            name: '{{field_name}}',
            label: '{{field_label}}',
            accessor: (r) => r.{{field_name}},
          ),{{/is_bool}}{{#is_datetime}}DateColumn<{{model_name}}>(
            name: '{{field_name}}',
            label: '{{field_label}}',
            accessor: (r) => r.{{field_name}},
            sortable: true,
          ),{{/is_datetime}}{{^is_bool}}{{^is_datetime}}TextColumn<{{model_name}}>(
            name: '{{field_name}}',
            label: '{{field_label}}',
            accessor: (r) => r.{{field_name}},
            searchable: true,
            sortable: true,
          ),{{/is_datetime}}{{/is_bool}}{{/fields_list}}
        ],
        rowActions: [
          RowAction.view<{{name.pascalCase()}}>((ctx, row) async {
            // navigation handled by ListRecordsPage default tap behavior
          }),
          RowAction.edit<{{name.pascalCase()}}>((ctx, row) async {
            // wire to router if needed
          }),
          RowAction.delete<{{name.pascalCase()}}>((ctx, row) async {
            await {{name.pascalCase()}}Services.dataSource.delete(row.id);
          }),
        ],
      );
}
