import 'package:flutter/material.dart';
import 'package:flutter_filament/flutter_filament.dart';

/// {{name.pascalCase()}}Page — generated by the `page` brick.
class {{name.pascalCase()}}Page extends FilamentPage {
  const {{name.pascalCase()}}Page({super.key});

  @override
  String get slug => '{{name_snake}}';

  @override
  String get title => '{{title}}';

  @override
  IconData get icon => Icons.{{icon}};{{#has_group}}

  @override
  String? get navigationGroup => '{{group}}';{{/has_group}}

  @override
  Widget buildBody(BuildContext context) {
    final theme = FilamentThemeScope.of(context);
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: theme.surface,
        border: Border.all(color: theme.border),
        borderRadius: BorderRadius.circular(theme.borderRadius),
      ),
      child: const Text('TODO: isi halaman {{title}}'),
    );
  }
}
