import 'package:flutter/material.dart';
import 'package:flutter_filament/flutter_filament.dart';

/// {{name.pascalCase()}}Widget — generated by the `widget` brick ({{type}}).
class {{name.pascalCase()}}Widget extends DashboardWidget {
  const {{name.pascalCase()}}Widget({super.key});

  @override
  int get columnSpan => {{columnSpan}};

  @override
  Widget build(BuildContext context) {
    {{#is_stat}}return const StatWidget(
      stats: [
        Stat(
          label: '{{name.titleCase()}}',
          value: '0',
          description: 'ubah nilai dari data source',
          icon: Icons.trending_up,
        ),
      ],
    );{{/is_stat}}{{#is_chart}}return const ChartWidget(
      title: '{{name.titleCase()}}',
      data: [
        ChartPoint('Sen', 12),
        ChartPoint('Sel', 18),
        ChartPoint('Rab', 7),
        ChartPoint('Kam', 24),
        ChartPoint('Jum', 16),
      ],
    );{{/is_chart}}{{#is_custom}}final theme = FilamentThemeScope.of(context);
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: theme.surface,
        border: Border.all(color: theme.border),
        borderRadius: BorderRadius.circular(theme.borderRadius),
      ),
      child: const Text('TODO: isi widget {{name.titleCase()}}'),
    );{{/is_custom}}
  }
}
