import 'package:equatable/equatable.dart';

/// {{name.pascalCase()}} — generated by the `model` brick.
class {{name.pascalCase()}} extends Equatable {
  final String id;{{#fields_list}}
  final {{nullable_type}} {{name.camelCase()}};{{/fields_list}}

  const {{name.pascalCase()}}({
    required this.id,{{#fields_list}}
    this.{{name.camelCase()}},{{/fields_list}}
  });

  factory {{name.pascalCase()}}.fromJson(Map<String, dynamic> json) => {{name.pascalCase()}}(
        id: json['id']?.toString() ?? '',{{#fields_list}}
        {{name.camelCase()}}: {{#is_datetime}}json['{{name.camelCase()}}'] is DateTime
            ? json['{{name.camelCase()}}'] as DateTime
            : json['{{name.camelCase()}}'] is String
                ? DateTime.tryParse(json['{{name.camelCase()}}'] as String)
                : null{{/is_datetime}}{{^is_datetime}}json['{{name.camelCase()}}'] as {{nullable_type}}{{/is_datetime}},{{/fields_list}}
      );

  Map<String, dynamic> toJson() => {
        'id': id,{{#fields_list}}
        '{{name.camelCase()}}': {{#is_datetime}}{{name.camelCase()}}?.toIso8601String(){{/is_datetime}}{{^is_datetime}}{{name.camelCase()}}{{/is_datetime}},{{/fields_list}}
      };

  {{name.pascalCase()}} copyWith({
    String? id,{{#fields_list}}
    {{nullable_type}} {{name.camelCase()}},{{/fields_list}}
  }) =>
      {{name.pascalCase()}}(
        id: id ?? this.id,{{#fields_list}}
        {{name.camelCase()}}: {{name.camelCase()}} ?? this.{{name.camelCase()}},{{/fields_list}}
      );

  @override
  List<Object?> get props => [id];
}
