import 'package:flutter_filament/flutter_filament.dart';
import '../../models/{{name_snake}}.dart';

/// DataSource for [{{name.pascalCase()}}] — generated by `resource` brick.
/// Swap [MemoryDataSource] for a Firestore/REST-backed implementation
/// when you wire the real backend.
class {{name.pascalCase()}}Services {
  static DataSource<{{name.pascalCase()}}> dataSource = MemoryDataSource<{{name.pascalCase()}}>(
    idOf: (r) => r.id,
    toMap: (r) => r.toJson(),
    fromMap: (m) => {{name.pascalCase()}}.fromJson(m),
    seed: const [],
  );
}
